""" Chatbot test """


# Import
import openai

# Key
openai.api_key = "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"


# Function to generate text from the language model
def text_generator(txt):

    # Getting response from language model
    response = openai.completions.create(

        # Model used
        engine = "text-davince-003",

        # Initial text of the conversation with chatbot.
        prompt = txt,

        # Response length used by the model.
        max_tokens = 150,

        # The returned text will not contain a stop sequence.
        stop = None,

        # A measure of the randomness of a text generated by your model. Its value is between 0 and 1.
        # Values ​​close to 1 mean the output is more random, while values ​​close to 0 mean the output is almost identifiable
        temperature = 0.8,
    )

return respose.choices[0].txt.strip()