# Import
import openai

# Key
openai.api_key = "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"

# Function to generate text from the language model
def text_generator(txt):

    # Getting response from language model
    response = openai.completions.create(

        # Model used
        engine="text-davinci-003",

        # Initial text of the conversation with chatbot.
        prompt=txt,

        # Response length used by the model.
        max_tokens=150,

        # The returned text will not contain a stop sequence.
        stop=None,

        # A measure of the randomness of a text generated by your model.
        # Its value is between 0 and 1. Values ​​close to 1 mean the output is more random,
        # while values ​​close to 0 mean the output is almost identifiable.
        temperature=0.8,
    )

    return response.choices[0].text.strip()

# Main function
def main():

    print("\nWelcome to GPT 4 Chatbot!")
    print("(Type 'exit' when you want to end the chat.)")

    while True:

        # Gets the question entered by the user.
        user_message = input("\nYou: ")

        # Validate the output response.
        if user_message.lower() == "exit":
            break

        # The message typed by the user goes to the 'prompt' variable.
        prompt = f"User: {user_message}\nChatbot:"

        # Captures the response of the model executed in the text_generator().
        chatbot_response = text_generator(prompt)

        # Prints the chatbot response.
        print(f"\nChatbot: {chatbot_response}")

if __name__ == "__main__":
    main()
